import type { Metadata } from 'next'
import './style.css'
import HomeLayout from '@/common/layout/home'

export const metadata: Metadata = {
  title: '李哈哈',
  description: 'Generated by create next app',
}

export default HomeLayout
